-- SETTING THE WORKING CONTEXT SO OBJECTS LAND IN THE RIGHT PLACE

USE WAREHOUSE EDP_WH;
USE DATABASE TFS_EDP;
USE SCHEMA STAGING;

-- FILE FORMAT FOR THE CSV FILES WE'LL BE LOADING INTO THE STAGING LAYER

CREATE OR REPLACE FILE FORMAT CSV_FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE
    COMMENT = 'CSV format for EDP source data files';

-- INTERNAL NAMED STAGE: LANDING ZONE INSIDE SNOWFLAKE FOR OUR FILES

CREATE STAGE IF NOT EXISTS EDP_STAGE
    FILE_FORMAT = CSV_FF
    COMMENT = 'Internal stage for landing source data files for EDP';