-- ============================================================
-- 01_staging / 03 -- Load stage files into staging tables
-- Transform form of COPY: inject _SOURCE_FILE + _LOAD_TS
-- ============================================================
USE WAREHOUSE EDP_WH;
USE DATABASE  TFS_EDP;
USE SCHEMA    STAGING;

COPY INTO STG_DEALER_DEALERS
FROM (SELECT $1,$2,$3,$4,$5,$6, METADATA$FILENAME, CURRENT_TIMESTAMP()
      FROM @EDP_STAGE/dealer_dealers.csv)
FILE_FORMAT = (FORMAT_NAME = CSV_FF) ON_ERROR = ABORT_STATEMENT;

COPY INTO STG_DEALER_VEHICLES
FROM (SELECT $1,$2,$3,$4,$5,$6, METADATA$FILENAME, CURRENT_TIMESTAMP()
      FROM @EDP_STAGE/dealer_vehicles.csv)
FILE_FORMAT = (FORMAT_NAME = CSV_FF) ON_ERROR = ABORT_STATEMENT;

COPY INTO STG_ORIGINATION_CUSTOMERS
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13, METADATA$FILENAME, CURRENT_TIMESTAMP()
      FROM @EDP_STAGE/origination_customers.csv)
FILE_FORMAT = (FORMAT_NAME = CSV_FF) ON_ERROR = ABORT_STATEMENT;

COPY INTO STG_ORIGINATION_APPLICATIONS
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11, METADATA$FILENAME, CURRENT_TIMESTAMP()
      FROM @EDP_STAGE/origination_applications.csv)
FILE_FORMAT = (FORMAT_NAME = CSV_FF) ON_ERROR = ABORT_STATEMENT;

COPY INTO STG_SERVICING_CONTRACTS
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12, METADATA$FILENAME, CURRENT_TIMESTAMP()
      FROM @EDP_STAGE/servicing_contracts.csv)
FILE_FORMAT = (FORMAT_NAME = CSV_FF) ON_ERROR = ABORT_STATEMENT;

COPY INTO STG_SERVICING_CUSTOMERS
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME, CURRENT_TIMESTAMP()
      FROM @EDP_STAGE/servicing_customers.csv)
FILE_FORMAT = (FORMAT_NAME = CSV_FF) ON_ERROR = ABORT_STATEMENT;

COPY INTO STG_SERVICING_CONTRACT_STATUS
FROM (SELECT $1,$2,$3,$4,$5, METADATA$FILENAME, CURRENT_TIMESTAMP()
      FROM @EDP_STAGE/servicing_contract_status.csv)
FILE_FORMAT = (FORMAT_NAME = CSV_FF) ON_ERROR = ABORT_STATEMENT;

COPY INTO STG_SERVICING_PAYMENTS
FROM (SELECT $1,$2,$3,$4,$5, METADATA$FILENAME, CURRENT_TIMESTAMP()
      FROM @EDP_STAGE/servicing_payments.csv)
FILE_FORMAT = (FORMAT_NAME = CSV_FF) ON_ERROR = ABORT_STATEMENT;